const clothes = [
  {
    id: 1,
    name: "hoodie",
    price: 7000,
    images: [
      "https://i.postimg.cc/9MgnsXBQ/hoodie-Black1234.png",
      "https://i.postimg.cc/nzpt4Y2R/hoodie-Black12.png",
      "https://i.postimg.cc/N01YvZ2D/Size-Hoodie1.png",
    ],
    img: "https://i.postimg.cc/9MgnsXBQ/hoodie-Black1234.png",
    sizes: ["M", "L", "XL"],
    type: [0, 1],
    availale: true,
    age: "new*",
    collection: "summer24",
    color: "черный",
    description:
      "Представляем вам уникальную толстовку от бренда Elen. Она выполнена в классическом черном цвете с элегантными нитями, которые добавляют ей изысканности и стиля. Внутренняя часть капюшона выделена ярким красным цветом, создающим контраст и привлекая внимание. Посередине толстовки размещен логотип Elen, который подчеркивает её премиальность и высокое качество. Этот абсолютно новый дизайн толстовки станет идеальным дополнением к любому образу и будет комфортен в любых условиях.",
  },
  {
    id: 2,
    name: "longsleeve orange",
    price: 4000,
    images: [
      "https://i.postimg.cc/J4HPyV35/elen-Long-Orange123.png",
      "https://i.postimg.cc/xTHfrR8C/Long-Orange-Full.png",
      "https://i.postimg.cc/y6TdZ3dj/Size-Long12.png",
    ],
    img: "https://i.postimg.cc/MGZ7jhC7/Long-Orange111.png",
    sizes: ["M", "L", "XL"],
    type: [0, 2],
    availale: true,
  },
  {
    id: 3,
    name: "longsleeve beige",
    price: 4000,
    images: [
      "https://i.postimg.cc/CKG2RTgQ/elen-Long-Being123.png",
      "https://imgbly.com/ib/4akiCaSUMH.png",
      "https://i.postimg.cc/y6TdZ3dj/Size-Long12.png",
    ],
    img: "https://i.postimg.cc/XJQ98Q0R/Long-White11.png",
    sizes: ["M", "L", "XL"],
    type: [0, 2],
    availale: true,
  },
  {
    id: 4,
    name: "longsleeve mint",
    price: 4000,
    images: [
      "https://i.postimg.cc/ZqHckTZ4/elen-Long-Mint123.png",
      "https://i.postimg.cc/CxXLrf6k/elen-long-mint.png",
      "https://i.postimg.cc/y6TdZ3dj/Size-Long12.png",
    ],
    img: "https://i.postimg.cc/RCcK0S83/Long-Mint1.png",
    sizes: ["M", "L", "XL"],
    type: [0, 2],
    availale: true,
  },
  {
    id: 5,
    name: "longsleeve red",
    price: 4000,
    images: [
      "https://i.postimg.cc/nrjYQBmh/elen-Long-Red123.png",
      "https://i.postimg.cc/qRs7sxKg/Long-Red-Full1.png",
      "https://i.postimg.cc/y6TdZ3dj/Size-Long12.png",
    ],
    img: "https://i.postimg.cc/QdSFTVkt/LongRed1.png",
    sizes: ["M", "L", "XL"],
    type: [0, 2],
    availale: true,
  },
  {
    id: 6,
    name: "t-shirt logo black",
    price: 1500,
    images: [
      "https://i.postimg.cc/rshrwmsN/elen-logo-black-1.png",
      "https://i.postimg.cc/9FyFR97N/elen-logo-black-1.png",
    ],
    img: "https://i.postimg.cc/q7d5CBM4/Black-Baby-Logo1.png",
    sizes: ["S", "M", "L", "XL"],
    type: [0, 3],
    availale: false,
  },
  {
    id: 7,
    name: "t-shirt logo white",
    price: 1500,
    images: [
      "https://i.postimg.cc/pL3KjpZ0/elen-logo-white-1.png",
      "https://i.postimg.cc/httDytvS/elen-logo-white-1.png",
    ],
    img: "https://i.postimg.cc/d03c0tW3/White-Baby-Logo1.png",
    sizes: ["S", "M", "L", "XL"],
    type: [0, 3],
    availale: false,
  },
  {
    id: 8,
    name: "t-shirt baby-logo black",
    price: 1500,
    images: [
      "https://i.postimg.cc/zfS3fBPH/elen-baby-logo-black-1.png",
      "https://i.postimg.cc/wjF5DcTT/elen-baby-logo-black-1.png",
    ],
    img: "https://i.postimg.cc/MTKBsGh6/elen-baby-logo-black-2.png",
    sizes: ["S", "M", "L", "XL"],
    type: [0, 3],
    availale: false,
  },
  {
    id: 9,
    name: "t-shirt baby-logo white",
    price: 1500,
    images: [
      "https://i.postimg.cc/Gp0s26LV/elen-baby-logo-white-1.png",
      "https://i.postimg.cc/L4Yk0jhs/elen-baby-logo-white-1.png",
    ],
    img: "https://i.postimg.cc/nhy3rNCK/elen-baby-logo-white.png",
    sizes: ["S", "M", "L", "XL"],
    type: [0, 3],
    availale: false,
  },
];

export default clothes;
